#!/usr/bin/env python3
# install-myrepos.py
"""
install-myrepos.py — Manage user-space installations of myrepos (mr).

This manager owns the full lifecycle of myrepos installations: acquisition,
placement, activation, and removal. It installs versioned, self-contained
artifacts and never touches the tool's own configuration (~/.mrconfig).

Upstream publishes no release tarballs and no semantic version tags, so
acquisition is a shallow git clone of the canonical repository at a ref,
and the version identity is upstream's Debian-native version read from
debian/changelog (for example 1.20180726).

Usage:
    install-myrepos.py --install [REF]    Install from upstream (default: HEAD)
    install-myrepos.py --switch VERSION   Point the env file at an installed version
    install-myrepos.py --status           Show installed versions and the active one
    install-myrepos.py --remove VERSION   Remove an installed version
    install-myrepos.py --upstream URL     Override the upstream repository for --install
    install-myrepos.py --version          Show this manager's version

What this manager owns:
    ~/.local/share/myrepos-tool/<version>/   Installed artifacts, one per version
    ~/.config/myrepos-tool/myrepos-tool.env  Active-version pointer, sourced by wrappers
    ~/.local/bin/mr, ~/.local/bin/webcheckout
                                             Generated wrapper scripts

What this manager does not touch:
    ~/.mrconfig                              mr's own configuration (owned by mr register)

Requires: Python 3.8+, git, and network access to the upstream for --install.
Runtime: mr requires perl and a POSIX shell; webcheckout additionally requires
the LWP::Simple and HTML::Parser Perl modules.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────────────

MANAGER_NAME     = "osat-fluent-myrepos-tool"
DEFAULT_UPSTREAM = "git://myrepos.branchable.com/"

SHARE_DIR  = Path.home() / ".local" / "share" / "myrepos-tool"
CONFIG_DIR = Path.home() / ".config" / "myrepos-tool"
ENV_FILE   = CONFIG_DIR / "myrepos-tool.env"
BIN_DIR    = Path.home() / ".local" / "bin"

# Commands to expose as wrappers: (command, relative path in artifact)
WRAPPED_COMMANDS = [
    ("mr",          "mr"),
    ("webcheckout", "webcheckout"),
]

_HERE         = Path(__file__).resolve().parent
_VERSION_FILE = _HERE / "VERSION"

DIR_MODE  = 0o700
FILE_MODE = 0o600
EXEC_MODE = 0o700

CHANGELOG_VERSION = re.compile(r"^myrepos \(([0-9][0-9.]*)\)")


# ── Small helpers ─────────────────────────────────────────────────────────────

def manager_version() -> str:
    try:
        return _VERSION_FILE.read_text(encoding="utf-8").strip()
    except FileNotFoundError:
        return "unknown"


def _tilde(path: Path) -> str:
    home = str(Path.home())
    s = str(path)
    return s.replace(home, "~", 1) if s.startswith(home) else s


def require(command: str, hint: str) -> None:
    """Exit if a required command is not on PATH."""
    if shutil.which(command) is None:
        print(f"[MYREPOS-TOOL ERROR] {command} not found on PATH. {hint}", file=sys.stderr)
        sys.exit(1)


def make_owner_only(path: Path) -> None:
    for root, dirs, files in os.walk(path):
        os.chmod(root, DIR_MODE)
        for f in files:
            p = Path(root) / f
            os.chmod(p, EXEC_MODE if os.access(p, os.X_OK) else FILE_MODE)


# ── Env file and wrappers ─────────────────────────────────────────────────────

def active_version() -> str:
    if not ENV_FILE.exists():
        return ""
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        if line.startswith("MYREPOS_TOOL_ROOT="):
            return Path(line.split("=", 1)[1].strip().strip('"')).name
    return ""


def write_env_file(version: str) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    os.chmod(CONFIG_DIR, DIR_MODE)
    root = SHARE_DIR / version
    ENV_FILE.write_text(
        f'# {_tilde(ENV_FILE)}\n'
        f'# Generated by {MANAGER_NAME}. Sourced by wrapper scripts at runtime.\n'
        f'MYREPOS_TOOL_ROOT="{root}"\n',
        encoding="utf-8",
    )
    os.chmod(ENV_FILE, FILE_MODE)


def write_wrappers() -> None:
    template = (_HERE / "scripts" / "nix" / "wrapper.template").read_text(encoding="utf-8")
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    for command, relpath in WRAPPED_COMMANDS:
        wrapper = BIN_DIR / command
        wrapper.write_text(
            template.format(command=command, relpath=relpath,
                            manager=MANAGER_NAME, env_file=_tilde(ENV_FILE)),
            encoding="utf-8",
        )
        os.chmod(wrapper, EXEC_MODE)
        print(f"  wrapper written:  {_tilde(wrapper)}  ✓")


# ── Lifecycle: install ────────────────────────────────────────────────────────

def read_upstream_version(tree: Path) -> str:
    """Read the Debian-native upstream version from debian/changelog."""
    changelog = tree / "debian" / "changelog"
    if not changelog.exists():
        print("[MYREPOS-TOOL ERROR] debian/changelog not found in the cloned tree;", file=sys.stderr)
        print("  cannot determine the upstream version.", file=sys.stderr)
        sys.exit(1)
    first = changelog.read_text(encoding="utf-8", errors="replace").splitlines()[0]
    m = CHANGELOG_VERSION.match(first)
    if not m:
        print("[MYREPOS-TOOL ERROR] Could not parse a version from debian/changelog.", file=sys.stderr)
        print(f"  First line was: {first!r}", file=sys.stderr)
        sys.exit(1)
    return m.group(1)


def generate_man_pages(tree: Path) -> None:
    """Best-effort man page generation into the artifact, as upstream's Makefile does."""
    if shutil.which("pod2man") is None:
        print("  pod2man not found; skipping man page generation.")
        return
    man_dir = tree / "man" / "man1"
    man_dir.mkdir(parents=True, exist_ok=True)
    for command, relpath in WRAPPED_COMMANDS:
        src = tree / relpath
        out = man_dir / f"{command}.1"
        result = subprocess.run(["pod2man", "-c", command, str(src)],
                                capture_output=True, text=True)
        if result.returncode == 0:
            out.write_text(result.stdout, encoding="utf-8")
            print(f"  man page built:   {_tilde(out)}  ✓")


def cmd_install(ref: str, upstream: str) -> int:
    require("git", "Acquisition is a git clone; install git first.")
    if shutil.which("perl") is None:
        print("[MYREPOS-TOOL WARNING] perl not found on PATH. mr will not run", file=sys.stderr)
        print("  without it. Installing anyway.", file=sys.stderr)

    print(f"[MYREPOS-TOOL] Installing myrepos from {upstream}" + (f" at {ref}" if ref else ""))
    with tempfile.TemporaryDirectory(prefix="myrepos-tool-") as tmp:
        clone_dir = Path(tmp) / "myrepos"
        cmd = ["git", "clone", "--depth", "1"]
        if ref:
            cmd += ["--branch", ref]
        cmd += [upstream, str(clone_dir)]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print("[MYREPOS-TOOL ERROR] git clone failed:", file=sys.stderr)
            print(result.stderr.strip(), file=sys.stderr)
            return 1

        version = read_upstream_version(clone_dir)
        install_root = SHARE_DIR / version
        if install_root.exists():
            print(f"[MYREPOS-TOOL] v{version} is already installed at {_tilde(install_root)}.")
            print("  Use --switch to activate it, or --remove first to reinstall.")
            return 1

        # Record provenance, then drop the git dependency from the artifact.
        head = subprocess.run(["git", "-C", str(clone_dir), "rev-parse", "HEAD"],
                              capture_output=True, text=True).stdout.strip()
        shutil.rmtree(clone_dir / ".git")
        (clone_dir / "PROVENANCE").write_text(
            f"upstream: {upstream}\nref: {ref or 'HEAD'}\ncommit: {head}\n",
            encoding="utf-8",
        )

        generate_man_pages(clone_dir)
        SHARE_DIR.mkdir(parents=True, exist_ok=True)
        os.chmod(SHARE_DIR, DIR_MODE)
        shutil.move(str(clone_dir), str(install_root))

    make_owner_only(install_root)
    print(f"  artifact placed:  {_tilde(install_root)}  ✓  (upstream version {version})")
    write_env_file(version)
    print(f"  env file written: {_tilde(ENV_FILE)}  ✓")
    write_wrappers()

    print()
    print(f"[MYREPOS-TOOL] myrepos {version} installed and active.")
    print("  Verify with:  mr --version")
    if str(BIN_DIR) not in os.environ.get("PATH", "").split(os.pathsep):
        print()
        print(f"  Note: {_tilde(BIN_DIR)} is not on your PATH. Add it with:")
        print('    export PATH="$HOME/.local/bin:$PATH"')
    return 0


# ── Lifecycle: switch, status, remove ─────────────────────────────────────────

def installed_versions():
    """Return installed version strings, newest first (dotted-numeric sort)."""
    if not SHARE_DIR.is_dir():
        return []
    found = []
    for entry in SHARE_DIR.iterdir():
        parts = entry.name.split(".")
        if entry.is_dir() and all(p.isdigit() for p in parts):
            found.append(tuple(int(p) for p in parts))
    return [".".join(str(n) for n in v) for v in sorted(found, reverse=True)]


def cmd_switch(version: str) -> int:
    if not (SHARE_DIR / version).is_dir():
        print(f"[MYREPOS-TOOL ERROR] {version} is not installed. Installed versions:", file=sys.stderr)
        for v in installed_versions():
            print(f"  {v}", file=sys.stderr)
        return 1
    write_env_file(version)
    write_wrappers()
    print(f"[MYREPOS-TOOL] Active version is now {version}.")
    return 0


def cmd_status() -> int:
    active = active_version()
    versions = installed_versions()
    print(f"[MYREPOS-TOOL] {MANAGER_NAME} {manager_version()}")
    print(f"  install root:  {_tilde(SHARE_DIR)}")
    print(f"  env file:      {_tilde(ENV_FILE)}" + ("" if ENV_FILE.exists() else "  (absent)"))
    if not versions:
        print("  installed:     none")
        return 0
    print("  installed:")
    for v in versions:
        print(f"    {v}" + ("  ← active" if v == active else ""))
    if active and active not in versions:
        print(f"  [WARNING] env file points at {active}, which is not installed.")
    return 0


def cmd_remove(version: str) -> int:
    install_root = SHARE_DIR / version
    if not install_root.is_dir():
        print(f"[MYREPOS-TOOL ERROR] {version} is not installed.", file=sys.stderr)
        return 1
    if version == active_version():
        print(f"[MYREPOS-TOOL ERROR] {version} is the active version. Switch to", file=sys.stderr)
        print("  another version first, then remove this one.", file=sys.stderr)
        return 1
    shutil.rmtree(install_root)
    print(f"[MYREPOS-TOOL] {version} removed.")
    return 0


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        prog="install-myrepos.py",
        description="Manage user-space installations of myrepos (mr).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  install-myrepos.py --install                 install upstream HEAD\n"
            "  install-myrepos.py --install 1.20180726      install a tagged ref\n"
            "  install-myrepos.py --switch 1.20180726       activate an installed version\n"
            "  install-myrepos.py --status                  show installed and active versions\n"
            "  install-myrepos.py --remove 1.20180726       remove a non-active version\n"
        ),
    )
    parser.add_argument("--install", nargs="?", const="", metavar="REF",
                        help="Install from upstream at REF (tag, branch, default HEAD).")
    parser.add_argument("--upstream", default=DEFAULT_UPSTREAM, metavar="URL",
                        help=f"Upstream repository for --install (default: {DEFAULT_UPSTREAM}).")
    parser.add_argument("--switch", metavar="VERSION",
                        help="Point the env file at an already-installed version.")
    parser.add_argument("--status", action="store_true",
                        help="Show installed versions and the active one.")
    parser.add_argument("--remove", metavar="VERSION",
                        help="Remove an installed version.")
    parser.add_argument("--version", action="store_true",
                        help="Show this manager's version and exit.")
    args = parser.parse_args()

    if args.version:
        print(f"{MANAGER_NAME} {manager_version()}")
        return 0
    if args.install is not None:
        return cmd_install(args.install, args.upstream)
    if args.switch:
        return cmd_switch(args.switch)
    if args.status:
        return cmd_status()
    if args.remove:
        return cmd_remove(args.remove)
    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
